#!/bin/bash

echo '# generated by get_syscall_table.sh'
echo
echo 'def syscall_table(name: str):'

grep NR /usr/include/x86_64-linux-gnu/asm/unistd_64.h | sed 's/^#define __NR_//' | \
while read NAME NR ; do
  # generate python code: return syscall id by its name
  echo "    if name == '$NAME':"
  echo "        return $NR"
  # also mkdir with format $NR:$NAME in syscall_profiles/
  mkdir -p syscall_profiles/$NR:$NAME
done
  echo '    raise ValueError("Unknown syscall name: %s" % name)'
