#ifndef __DEEPLOG_VMLINUX_METADATA_H__
#define __DEEPLOG_VMLINUX_METADATA_H__
/*
 * This file is auto-generated by vmlinux_code_loader.py: python3 host-os/vmlinux_code_loader.py
 */
#include "libpt.h"

#define NR_LINUX_CODESECTIONS 4

#define VMLINUX_METADATA_PATH "/home/chuqi/GitHub/deeplog-kern/host-os/outputs/vmlinux_code.metadata"

static const char *LINUX_VMEM_PATHS[NR_LINUX_CODESECTIONS] = {
    "/home/chuqi/GitHub/deeplog-kern/host-os/outputs/vmlinux_code.vmem0",
    "/home/chuqi/GitHub/deeplog-kern/host-os/outputs/vmlinux_code.vmem1",
    "/home/chuqi/GitHub/deeplog-kern/host-os/outputs/vmlinux_code.vmem2",
    "/home/chuqi/GitHub/deeplog-kern/host-os/outputs/vmlinux_code.vmem3",
};


#endif
