from pathlib import Path
from typing import List, Tuple
import sys

print(Path(__file__))
print(Path(__file__).parent.parent)
DEFAULT_TEMPLATE_DIR = Path(__file__).parent.parent/"guest"/"vmhome"/"kftracer"/"ftrace"/"out_UD2"

# To be specific by our command line argument for a sensitive process
# DEFAULT_WHOLE_PG_FILE = DEFAULT_TEMPLATE_DIR #/ "whole_page_code.txt"
# DEFAULT_SUB_PG_FILE = DEFAULT_TEMPLATE_DIR #/ "ud2_sections.txt"

DEFAULT_DST_FILE = Path(__file__).parent / "kvm" / "mmu" / "template.h"
print(DEFAULT_DST_FILE)

def format_string(nr_indent, indent, string):
    return nr_indent * indent + string + "\n"

def __template_head() -> str:
    head = ""
    indent = "    "
    nr_indent = 0
    head += format_string(nr_indent, indent, "#ifndef __DEEPLOG_TEMPLATE_H__")
    head += format_string(nr_indent, indent, "#define __DEEPLOG_TEMPLATE_H__")
    head += format_string(nr_indent, indent, "/*")
    head += format_string(nr_indent, indent, " * This file is auto-generated by template_gen.py: python3 host-os/template_gen.py")
    head += format_string(nr_indent, indent, " */")
    head += format_string(nr_indent, indent, "#include \"libept.h\"")
    head += format_string(nr_indent, indent, "")
    return head

def __template_init_macro(max_id) -> str:
    macro = ""
    indent = "    "
    nr_indent = 0
    macro += format_string(nr_indent, indent, "#define DEEPLOG_TEMPLATE_INIT(ctx, id) \\")
    nr_indent += 1
    # use switch case
    macro += format_string(nr_indent, indent, "switch(id) { \\")
    nr_indent += 1
    for i in range(0, max_id):
        macro += format_string(nr_indent, indent, f"case {i}: init_deeplog_ctx_{i}(ctx); break; \\")
    macro += format_string(nr_indent, indent, "default: init_deeplog_ctx_default(ctx); break; \\")
    nr_indent -= 1
    macro += format_string(nr_indent, indent, "}")
    return macro

def __template_init_func(id: int, whole_pages: List, sub_page_ranges: List[Tuple]) -> str:
    nr_whole_pages, nr_sub_pages = len(whole_pages), len(sub_page_ranges)
    func = ""
    indent = "    "
    nr_indent = 0
    # use .format
    func += format_string(nr_indent, indent, f"static inline void init_deeplog_ctx_{id}(deeplog_ctx_t *ctx)")
    func += format_string(nr_indent, indent, "{")
    nr_indent += 1
    # init ctx's `dlctx_ud2_whole_pgs_t` and `dlctx_ud2_sub_pgs_t`
    func += format_string(nr_indent, indent, f"ctx->ud2_whole_pages.nr = {nr_whole_pages};")
    if nr_whole_pages == 0:
        func += format_string(nr_indent, indent, f"ctx->ud2_whole_pages.ud2_pages = NULL;")
    else:
        func += format_string(nr_indent, indent, f"ctx->ud2_whole_pages.ud2_pages = (u64 *)kmalloc(sizeof(u64) * {nr_whole_pages}, GFP_KERNEL);")
    func += "\n"
    func += format_string(nr_indent, indent, f"ctx->ud2_sub_pages.nr = {nr_sub_pages};")
    if nr_sub_pages == 0:
        func += format_string(nr_indent, indent, f"ctx->ud2_sub_pages.ud2_page_starts = NULL;")
        func += format_string(nr_indent, indent, f"ctx->ud2_sub_pages.ud2_page_ends = NULL;")
    else:
        func += format_string(nr_indent, indent, f"ctx->ud2_sub_pages.ud2_page_starts = (u64 *)kmalloc(sizeof(u64) * {nr_sub_pages}, GFP_KERNEL);")
        func += format_string(nr_indent, indent, f"ctx->ud2_sub_pages.ud2_page_ends = (u64 *)kmalloc(sizeof(u64) * {nr_sub_pages}, GFP_KERNEL);")
        func += "\n"
    # assign whole_pages
    if nr_whole_pages != 0:
        for i in range(0, nr_whole_pages):
            func += format_string(nr_indent, indent, f"ctx->ud2_whole_pages.ud2_pages[{i}] = {whole_pages[i]};")

    #assign sub_pages
    if nr_sub_pages != 0:
        func += "\n"
        for i in range(0, nr_sub_pages):
            func += format_string(nr_indent, indent, f"ctx->ud2_sub_pages.ud2_page_starts[{i}] = {sub_page_ranges[i][0]};")
            func += format_string(nr_indent, indent, f"ctx->ud2_sub_pages.ud2_page_ends[{i}] = {sub_page_ranges[i][1]};")
    nr_indent -= 1
    func += format_string(nr_indent, indent, "}")
    return func

def __template_default_init_func() -> str:
    func = ""
    indent = "    "
    nr_indent = 0
    func += format_string(nr_indent, indent, f"static inline void init_deeplog_ctx_default(deeplog_ctx_t *ctx)")
    func += format_string(nr_indent, indent, "{")
    nr_indent += 1

    func += format_string(nr_indent, indent, f"ctx->ud2_whole_pages.nr = 0;")
    func += format_string(nr_indent, indent, f"ctx->ud2_whole_pages.ud2_pages = NULL;")
    func += "\n"
    func += format_string(nr_indent, indent, f"ctx->ud2_sub_pages.nr = 0;")
    func += format_string(nr_indent, indent, f"ctx->ud2_sub_pages.ud2_page_starts = NULL;")
    func += format_string(nr_indent, indent, f"ctx->ud2_sub_pages.ud2_page_ends = NULL;")
    nr_indent -= 1
    func += format_string(nr_indent, indent, "}")
    return func

def __pair_elements(lst):
    if len(lst) % 2 != 0:
        raise ValueError("len(lst) must be even")
    return [(lst[i], lst[i+1]) for i in range(0, len(lst), 2)]

def template_extract():
    f_whole_pg = open(DEFAULT_WHOLE_PG_FILE, "r")
    lines_whole_pg = f_whole_pg.readlines()

    f_sub_pg = open(DEFAULT_SUB_PG_FILE, "r")
    lines_sub_pg = f_sub_pg.readlines()

    f_template = open(DEFAULT_DST_FILE, "w")

    assert(len(lines_whole_pg) == len(lines_sub_pg))
    func_max_id = len(lines_whole_pg)
    
    template = ""
    template += __template_head()

    # each line is a deeplog_ctx
    for i in range(0, len(lines_whole_pg)):
        # extract whole_pages to be UD2 of this context
        whole_pgs = lines_whole_pg[i].strip().strip(",")
        if not whole_pgs:
            whole_pgs = []
        else:
            whole_pgs = whole_pgs.split(",")

        # extract sub_page ranges to be UD2 of this context
        sub_pg_ranges = lines_sub_pg[i].strip().strip(",")
        if not sub_pg_ranges:
            sub_pg_ranges = []
        else:
            sub_pg_ranges = sub_pg_ranges.split(",")
            sub_pg_ranges = __pair_elements(sub_pg_ranges)

        template += "\n"
        template += __template_init_func(i, whole_pgs, sub_pg_ranges)

    template += "\n"
    # default init func
    template += __template_default_init_func()
    template += "\n"
    # switch-to-init macro
    template += __template_init_macro(func_max_id)
    template += "#endif\n"
    f_template.write(template)
    f_whole_pg.close()
    f_sub_pg.close()
    f_template.close()
    print(template)


if __name__ == "__main__":
    if (len(sys.argv) < 2):
        print("Usage: python3 template_gen.py <target_profiled_process_name> <(optional) kvm>")
        exit(1)
    
    targ_proc = sys.argv[1]
    
    if (len(sys.argv) == 3 and sys.argv[2] == "kvm"):
        print(f"[Info target process {targ_proc}]: using kvm template")
        DEFAULT_WHOLE_PG_FILE = DEFAULT_TEMPLATE_DIR/str(targ_proc)/"kvm_data"/"whole_page_code.txt"
        DEFAULT_SUB_PG_FILE = DEFAULT_TEMPLATE_DIR/str(targ_proc)/"kvm_data"/"ud2_sections.txt"
    else:
        DEFAULT_WHOLE_PG_FILE = DEFAULT_TEMPLATE_DIR/str(targ_proc)/"whole_page_code.txt"
        DEFAULT_SUB_PG_FILE = DEFAULT_TEMPLATE_DIR/str(targ_proc)/"ud2_sections.txt"

    if not DEFAULT_WHOLE_PG_FILE.exists():
        print(f"[Error target process {targ_proc}]: {DEFAULT_WHOLE_PG_FILE} does not exist")
        exit(1)
    
    if not DEFAULT_SUB_PG_FILE.exists():
        print(f"[Error target process {targ_proc}]: {DEFAULT_SUB_PG_FILE} does not exist")
        exit(1)

    template_extract()

    # succ
    print(f"[Succ target process {targ_proc}] KVM CF-profiling template done.")
    print(f"Profile dir: {DEFAULT_WHOLE_PG_FILE.parent}")
    print(f"Template is generated to {DEFAULT_DST_FILE}")
    print(f"Now please rebuild kvm by executing: repo-path/host-os/rebuild-kvm.sh")