import os

# generated by get_syscall_table.sh

def syscall_table(name: str):
    if name == 'read':
        return 0
    if name == 'write':
        return 1
    if name == 'open':
        return 2
    if name == 'close':
        return 3
    if name == 'stat':
        return 4
    if name == 'fstat':
        return 5
    if name == 'lstat':
        return 6
    if name == 'poll':
        return 7
    if name == 'lseek':
        return 8
    if name == 'mmap':
        return 9
    if name == 'mprotect':
        return 10
    if name == 'munmap':
        return 11
    if name == 'brk':
        return 12
    if name == 'rt_sigaction':
        return 13
    if name == 'rt_sigprocmask':
        return 14
    if name == 'rt_sigreturn':
        return 15
    if name == 'ioctl':
        return 16
    if name == 'pread64':
        return 17
    if name == 'pwrite64':
        return 18
    if name == 'readv':
        return 19
    if name == 'writev':
        return 20
    if name == 'access':
        return 21
    if name == 'pipe':
        return 22
    if name == 'select':
        return 23
    if name == 'sched_yield':
        return 24
    if name == 'mremap':
        return 25
    if name == 'msync':
        return 26
    if name == 'mincore':
        return 27
    if name == 'madvise':
        return 28
    if name == 'shmget':
        return 29
    if name == 'shmat':
        return 30
    if name == 'shmctl':
        return 31
    if name == 'dup':
        return 32
    if name == 'dup2':
        return 33
    if name == 'pause':
        return 34
    if name == 'nanosleep':
        return 35
    if name == 'getitimer':
        return 36
    if name == 'alarm':
        return 37
    if name == 'setitimer':
        return 38
    if name == 'getpid':
        return 39
    if name == 'sendfile':
        return 40
    if name == 'socket':
        return 41
    if name == 'connect':
        return 42
    if name == 'accept':
        return 43
    if name == 'sendto':
        return 44
    if name == 'recvfrom':
        return 45
    if name == 'sendmsg':
        return 46
    if name == 'recvmsg':
        return 47
    if name == 'shutdown':
        return 48
    if name == 'bind':
        return 49
    if name == 'listen':
        return 50
    if name == 'getsockname':
        return 51
    if name == 'getpeername':
        return 52
    if name == 'socketpair':
        return 53
    if name == 'setsockopt':
        return 54
    if name == 'getsockopt':
        return 55
    if name == 'clone':
        return 56
    if name == 'fork':
        return 57
    if name == 'vfork':
        return 58
    if name == 'execve':
        return 59
    if name == 'exit':
        return 60
    if name == 'wait4':
        return 61
    if name == 'kill':
        return 62
    if name == 'uname':
        return 63
    if name == 'semget':
        return 64
    if name == 'semop':
        return 65
    if name == 'semctl':
        return 66
    if name == 'shmdt':
        return 67
    if name == 'msgget':
        return 68
    if name == 'msgsnd':
        return 69
    if name == 'msgrcv':
        return 70
    if name == 'msgctl':
        return 71
    if name == 'fcntl':
        return 72
    if name == 'flock':
        return 73
    if name == 'fsync':
        return 74
    if name == 'fdatasync':
        return 75
    if name == 'truncate':
        return 76
    if name == 'ftruncate':
        return 77
    if name == 'getdents':
        return 78
    if name == 'getcwd':
        return 79
    if name == 'chdir':
        return 80
    if name == 'fchdir':
        return 81
    if name == 'rename':
        return 82
    if name == 'mkdir':
        return 83
    if name == 'rmdir':
        return 84
    if name == 'creat':
        return 85
    if name == 'link':
        return 86
    if name == 'unlink':
        return 87
    if name == 'symlink':
        return 88
    if name == 'readlink':
        return 89
    if name == 'chmod':
        return 90
    if name == 'fchmod':
        return 91
    if name == 'chown':
        return 92
    if name == 'fchown':
        return 93
    if name == 'lchown':
        return 94
    if name == 'umask':
        return 95
    if name == 'gettimeofday':
        return 96
    if name == 'getrlimit':
        return 97
    if name == 'getrusage':
        return 98
    if name == 'sysinfo':
        return 99
    if name == 'times':
        return 100
    if name == 'ptrace':
        return 101
    if name == 'getuid':
        return 102
    if name == 'syslog':
        return 103
    if name == 'getgid':
        return 104
    if name == 'setuid':
        return 105
    if name == 'setgid':
        return 106
    if name == 'geteuid':
        return 107
    if name == 'getegid':
        return 108
    if name == 'setpgid':
        return 109
    if name == 'getppid':
        return 110
    if name == 'getpgrp':
        return 111
    if name == 'setsid':
        return 112
    if name == 'setreuid':
        return 113
    if name == 'setregid':
        return 114
    if name == 'getgroups':
        return 115
    if name == 'setgroups':
        return 116
    if name == 'setresuid':
        return 117
    if name == 'getresuid':
        return 118
    if name == 'setresgid':
        return 119
    if name == 'getresgid':
        return 120
    if name == 'getpgid':
        return 121
    if name == 'setfsuid':
        return 122
    if name == 'setfsgid':
        return 123
    if name == 'getsid':
        return 124
    if name == 'capget':
        return 125
    if name == 'capset':
        return 126
    if name == 'rt_sigpending':
        return 127
    if name == 'rt_sigtimedwait':
        return 128
    if name == 'rt_sigqueueinfo':
        return 129
    if name == 'rt_sigsuspend':
        return 130
    if name == 'sigaltstack':
        return 131
    if name == 'utime':
        return 132
    if name == 'mknod':
        return 133
    if name == 'uselib':
        return 134
    if name == 'personality':
        return 135
    if name == 'ustat':
        return 136
    if name == 'statfs':
        return 137
    if name == 'fstatfs':
        return 138
    if name == 'sysfs':
        return 139
    if name == 'getpriority':
        return 140
    if name == 'setpriority':
        return 141
    if name == 'sched_setparam':
        return 142
    if name == 'sched_getparam':
        return 143
    if name == 'sched_setscheduler':
        return 144
    if name == 'sched_getscheduler':
        return 145
    if name == 'sched_get_priority_max':
        return 146
    if name == 'sched_get_priority_min':
        return 147
    if name == 'sched_rr_get_interval':
        return 148
    if name == 'mlock':
        return 149
    if name == 'munlock':
        return 150
    if name == 'mlockall':
        return 151
    if name == 'munlockall':
        return 152
    if name == 'vhangup':
        return 153
    if name == 'modify_ldt':
        return 154
    if name == 'pivot_root':
        return 155
    if name == '_sysctl':
        return 156
    if name == 'prctl':
        return 157
    if name == 'arch_prctl':
        return 158
    if name == 'adjtimex':
        return 159
    if name == 'setrlimit':
        return 160
    if name == 'chroot':
        return 161
    if name == 'sync':
        return 162
    if name == 'acct':
        return 163
    if name == 'settimeofday':
        return 164
    if name == 'mount':
        return 165
    if name == 'umount2':
        return 166
    if name == 'swapon':
        return 167
    if name == 'swapoff':
        return 168
    if name == 'reboot':
        return 169
    if name == 'sethostname':
        return 170
    if name == 'setdomainname':
        return 171
    if name == 'iopl':
        return 172
    if name == 'ioperm':
        return 173
    if name == 'create_module':
        return 174
    if name == 'init_module':
        return 175
    if name == 'delete_module':
        return 176
    if name == 'get_kernel_syms':
        return 177
    if name == 'query_module':
        return 178
    if name == 'quotactl':
        return 179
    if name == 'nfsservctl':
        return 180
    if name == 'getpmsg':
        return 181
    if name == 'putpmsg':
        return 182
    if name == 'afs_syscall':
        return 183
    if name == 'tuxcall':
        return 184
    if name == 'security':
        return 185
    if name == 'gettid':
        return 186
    if name == 'readahead':
        return 187
    if name == 'setxattr':
        return 188
    if name == 'lsetxattr':
        return 189
    if name == 'fsetxattr':
        return 190
    if name == 'getxattr':
        return 191
    if name == 'lgetxattr':
        return 192
    if name == 'fgetxattr':
        return 193
    if name == 'listxattr':
        return 194
    if name == 'llistxattr':
        return 195
    if name == 'flistxattr':
        return 196
    if name == 'removexattr':
        return 197
    if name == 'lremovexattr':
        return 198
    if name == 'fremovexattr':
        return 199
    if name == 'tkill':
        return 200
    if name == 'time':
        return 201
    if name == 'futex':
        return 202
    if name == 'sched_setaffinity':
        return 203
    if name == 'sched_getaffinity':
        return 204
    if name == 'set_thread_area':
        return 205
    if name == 'io_setup':
        return 206
    if name == 'io_destroy':
        return 207
    if name == 'io_getevents':
        return 208
    if name == 'io_submit':
        return 209
    if name == 'io_cancel':
        return 210
    if name == 'get_thread_area':
        return 211
    if name == 'lookup_dcookie':
        return 212
    if name == 'epoll_create':
        return 213
    if name == 'epoll_ctl_old':
        return 214
    if name == 'epoll_wait_old':
        return 215
    if name == 'remap_file_pages':
        return 216
    if name == 'getdents64':
        return 217
    if name == 'set_tid_address':
        return 218
    if name == 'restart_syscall':
        return 219
    if name == 'semtimedop':
        return 220
    if name == 'fadvise64':
        return 221
    if name == 'timer_create':
        return 222
    if name == 'timer_settime':
        return 223
    if name == 'timer_gettime':
        return 224
    if name == 'timer_getoverrun':
        return 225
    if name == 'timer_delete':
        return 226
    if name == 'clock_settime':
        return 227
    if name == 'clock_gettime':
        return 228
    if name == 'clock_getres':
        return 229
    if name == 'clock_nanosleep':
        return 230
    if name == 'exit_group':
        return 231
    if name == 'epoll_wait':
        return 232
    if name == 'epoll_ctl':
        return 233
    if name == 'tgkill':
        return 234
    if name == 'utimes':
        return 235
    if name == 'vserver':
        return 236
    if name == 'mbind':
        return 237
    if name == 'set_mempolicy':
        return 238
    if name == 'get_mempolicy':
        return 239
    if name == 'mq_open':
        return 240
    if name == 'mq_unlink':
        return 241
    if name == 'mq_timedsend':
        return 242
    if name == 'mq_timedreceive':
        return 243
    if name == 'mq_notify':
        return 244
    if name == 'mq_getsetattr':
        return 245
    if name == 'kexec_load':
        return 246
    if name == 'waitid':
        return 247
    if name == 'add_key':
        return 248
    if name == 'request_key':
        return 249
    if name == 'keyctl':
        return 250
    if name == 'ioprio_set':
        return 251
    if name == 'ioprio_get':
        return 252
    if name == 'inotify_init':
        return 253
    if name == 'inotify_add_watch':
        return 254
    if name == 'inotify_rm_watch':
        return 255
    if name == 'migrate_pages':
        return 256
    if name == 'openat':
        return 257
    if name == 'mkdirat':
        return 258
    if name == 'mknodat':
        return 259
    if name == 'fchownat':
        return 260
    if name == 'futimesat':
        return 261
    if name == 'newfstatat':
        return 262
    if name == 'unlinkat':
        return 263
    if name == 'renameat':
        return 264
    if name == 'linkat':
        return 265
    if name == 'symlinkat':
        return 266
    if name == 'readlinkat':
        return 267
    if name == 'fchmodat':
        return 268
    if name == 'faccessat':
        return 269
    if name == 'pselect6':
        return 270
    if name == 'ppoll':
        return 271
    if name == 'unshare':
        return 272
    if name == 'set_robust_list':
        return 273
    if name == 'get_robust_list':
        return 274
    if name == 'splice':
        return 275
    if name == 'tee':
        return 276
    if name == 'sync_file_range':
        return 277
    if name == 'vmsplice':
        return 278
    if name == 'move_pages':
        return 279
    if name == 'utimensat':
        return 280
    if name == 'epoll_pwait':
        return 281
    if name == 'signalfd':
        return 282
    if name == 'timerfd_create':
        return 283
    if name == 'eventfd':
        return 284
    if name == 'fallocate':
        return 285
    if name == 'timerfd_settime':
        return 286
    if name == 'timerfd_gettime':
        return 287
    if name == 'accept4':
        return 288
    if name == 'signalfd4':
        return 289
    if name == 'eventfd2':
        return 290
    if name == 'epoll_create1':
        return 291
    if name == 'dup3':
        return 292
    if name == 'pipe2':
        return 293
    if name == 'inotify_init1':
        return 294
    if name == 'preadv':
        return 295
    if name == 'pwritev':
        return 296
    if name == 'rt_tgsigqueueinfo':
        return 297
    if name == 'perf_event_open':
        return 298
    if name == 'recvmmsg':
        return 299
    if name == 'fanotify_init':
        return 300
    if name == 'fanotify_mark':
        return 301
    if name == 'prlimit64':
        return 302
    if name == 'name_to_handle_at':
        return 303
    if name == 'open_by_handle_at':
        return 304
    if name == 'clock_adjtime':
        return 305
    if name == 'syncfs':
        return 306
    if name == 'sendmmsg':
        return 307
    if name == 'setns':
        return 308
    if name == 'getcpu':
        return 309
    if name == 'process_vm_readv':
        return 310
    if name == 'process_vm_writev':
        return 311
    if name == 'kcmp':
        return 312
    if name == 'finit_module':
        return 313
    if name == 'sched_setattr':
        return 314
    if name == 'sched_getattr':
        return 315
    if name == 'renameat2':
        return 316
    if name == 'seccomp':
        return 317
    if name == 'getrandom':
        return 318
    if name == 'memfd_create':
        return 319
    if name == 'kexec_file_load':
        return 320
    if name == 'bpf':
        return 321
    if name == 'execveat':
        return 322
    if name == 'userfaultfd':
        return 323
    if name == 'membarrier':
        return 324
    if name == 'mlock2':
        return 325
    if name == 'copy_file_range':
        return 326
    if name == 'preadv2':
        return 327
    if name == 'pwritev2':
        return 328
    if name == 'pkey_mprotect':
        return 329
    if name == 'pkey_alloc':
        return 330
    if name == 'pkey_free':
        return 331
    if name == 'statx':
        return 332
    if name == 'io_pgetevents':
        return 333
    if name == 'rseq':
        return 334
    if name == 'pidfd_send_signal':
        return 424
    if name == 'io_uring_setup':
        return 425
    if name == 'io_uring_enter':
        return 426
    if name == 'io_uring_register':
        return 427
    if name == 'open_tree':
        return 428
    if name == 'move_mount':
        return 429
    if name == 'fsopen':
        return 430
    if name == 'fsconfig':
        return 431
    if name == 'fsmount':
        return 432
    if name == 'fspick':
        return 433
    if name == 'pidfd_open':
        return 434
    if name == 'clone3':
        return 435
    if name == 'close_range':
        return 436
    if name == 'openat2':
        return 437
    if name == 'pidfd_getfd':
        return 438
    if name == 'faccessat2':
        return 439
    if name == 'process_madvise':
        return 440
    if name == 'epoll_pwait2':
        return 441
    if name == 'mount_setattr':
        return 442
    if name == 'quotactl_fd':
        return 443
    if name == 'landlock_create_ruleset':
        return 444
    if name == 'landlock_add_rule':
        return 445
    if name == 'landlock_restrict_self':
        return 446
    if name == 'memfd_secret':
        return 447
    if name == 'process_mrelease':
        return 448
    raise ValueError("Unknown syscall name: %s" % name)

base_dir = "syscall_procs"
os.makedirs(base_dir, exist_ok=True)